version: "3.9"
services:
  api:
    image: internal-sql-api:1.0.1
    container_name: internal-sql-api
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [ edge ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    image: caddy:2-alpine
    container_name: reverse-proxy
    depends_on: [ api ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks: [ edge ]

volumes:
  caddy_data:
  caddy_config:

networks:
  edge:
    driver: bridge
