version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: YourStrong!Passw0rd
      DB_NAME: DemoAPI

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
